# Generated by Django 2.2 on 2020-10-05 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logos', models.ImageField(upload_to='uploads')),
            ],
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='uploads/')),
                ('category', models.CharField(choices=[('corporate', 'admin'), ('sports', 'editor'), ('weddings', 'viewer'), ('documentaries', 'documentaries')], max_length=50)),
            ],
        ),
    ]
