# Generated by Django 2.2 on 2020-10-07 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hawi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='category',
            field=models.CharField(choices=[('corporate', 'corporate'), ('sports', 'sports'), ('weddings', 'weddings'), ('documentaries', 'documentaries')], max_length=50),
        ),
    ]
